name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build burnmem
      working-directory: ./burnmem
      run: go build -v

    - name: Build watchdog
      run: go build -v ./...

    - name: 'Upload burnmem'
      uses: actions/upload-artifact@v3
      with:
        name: burnmem
        path: burnmem/burnmem.exe
        retention-days: 1
  
    - name: 'Upload watchdog'
      uses: actions/upload-artifact@v3
      with:
        name: burnmem_watchdog
        path: burnmem_watchdog.exe
        retention-days: 1
